apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-deployment
spec:
  selector:
    matchLabels:
      app: hpa-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: hpa-deployment
    spec:
      containers:
      - name: hpa-deployment
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "32Mi"
            cpu: "16m"
          requests:
            memory: "8Mi"
            cpu: "4m"
        command: ["/bin/sh"]
        args:
          - "-c"
          - |
            while true; do
              dd if=/dev/urandom of=/dev/null bs=8M count=3 &
              dd if=/dev/urandom of=/dev/null bs=8M count=3 &
              sleep 60
            done