apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: housekeeping-clusterrole
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete"]