apiVersion: v1
kind: Service
metadata:
  name: nginx-backend-service
spec:
  selector:
    app: nginx-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30002
  type: NodePort