apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'cronjob-deployment'
spec:
  selector:
    matchLabels:
      app: cronjob-deployment
  replicas: 3
  template:
    metadata:
      labels:
        app: cronjob-deployment
    spec:
      containers:
        - name: container
          image: >-
            nginx:latest
          ports:
            - containerPort: 8080
              protocol: TCP
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%