apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cronjob-deployment-admin-binding
subjects:
- kind: ServiceAccount
  name: cronjob-deployment
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cronjob-deployment-admin